name: compound
channels:
  - conda-forge
  - nodefaults

dependencies:
  - r-base
  - r-ggplot2
  - r-loader
  - r-transformer
  - r-visualizer
  - r-downscaler
  - r-irkernel
  - r-geoprocessor
  - jupyterlab
  - r-remotes
